import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const bookAppointmentStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40,
  },
  doctorCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    padding: 16,
    marginBottom: 16,
    shadowColor: 'rgba(15, 23, 42, 0.06)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
  },
  doctorCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 12,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardHeaderIconBadge: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardHeaderTitle: {
    fontSize: 12,
    fontWeight: '500',
    color: theme.colors.textMuted,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.colors.mintBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
  },
  verifiedBadgeText: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.colors.primary,
    letterSpacing: 0.2,
  },
  doctorContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  doctorAvatarWrapper: {
    position: 'relative',
  },
  doctorAvatarImage: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1.5,
    borderColor: theme.colors.mintBdr,
  },
  doctorAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1.5,
    borderColor: theme.colors.mintBdr,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doctorAvatarText: {
    color: theme.colors.primaryDark,
    fontWeight: '500',
    fontSize: 14,
  },
  avatarVerifiedBadge: {
    position: 'absolute',
    bottom: -1,
    right: -1,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: theme.colors.primary,
    borderWidth: 1.5,
    borderColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doctorDetails: {
    flex: 1,
    minWidth: 0,
  },
  doctorName: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.textPrimary,
    marginBottom: 3,
  },
  doctorSpecializationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  doctorSpecialization: {
    fontSize: 12,
    color: theme.colors.primaryDark,
    fontWeight: '500',
  },
  doctorMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  doctorMetaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.colors.surfaceSecondary,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    maxWidth: '100%',
  },
  doctorMetaText: {
    fontSize: 8,
    fontWeight: '500',
    color: theme.colors.textSecondary,
  },
  doctorSubline: {
    fontSize: 10,
    color: theme.colors.textMuted,
  },
  sectionLabel: {
    fontSize: 12,
    color: theme.colors.textMuted,
    letterSpacing: 0.8,
    fontWeight: '500',
    marginBottom: 10,
    marginTop: 8,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.colors.primaryDark,
    marginTop: 14,
    marginBottom: 6,
  },
  optionalHint: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.colors.textMuted,
  },
  patientCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    marginBottom: 16,
    shadowColor: 'rgba(15, 23, 42, 0.06)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
    gap: 12,
  },
  patientInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  patientAvatarWrapper: {
    position: 'relative',
  },
  patientAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1.5,
    borderColor: theme.colors.mintBdr,
    alignItems: 'center',
    justifyContent: 'center',
  },
  patientAvatarText: {
    color: theme.colors.primaryDark,
    fontWeight: '500',
    fontSize: 14,
  },
  patientDetails: {
    flex: 1,
    minWidth: 0,
  },
  patientName: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.textPrimary,
    marginBottom: 4,
  },
  patientIdBadge: {
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.surfaceSecondary,
    paddingHorizontal: 8,
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  patientId: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.colors.textSecondary,
    letterSpacing: 0.2,
  },
  patientActiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.colors.mintBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
  },
  patientActiveText: {
    fontSize: 10,
    fontWeight: '500',
    color: theme.colors.primary,
    letterSpacing: 0.2,
  },
  changeBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: theme.colors.primarySoft,
  },
  changeBtnText: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.colors.primaryDark,
  },
  consultationRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  consultationChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 12,
    paddingVertical: 12,
  },
  consultationChipActive: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primary,
  },
  consultationChipDisabled: {
    opacity: 0.5,
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primaryLight,
  },
  consultationChipText: {
    fontSize: 12,
    fontWeight: '500',
    color: theme.colors.textSecondary,
  },
  consultationChipTextActive: {
    color: theme.colors.primaryDark,
    fontWeight: '500',
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  dateChipCard: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    minWidth: 78,
  },
  dateChipCardActive: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primary,
  },
  dateChipTopText: {
    fontSize: 12,
    fontWeight: '500',
    color: theme.colors.textSecondary,
    marginBottom: 2,
  },
  dateChipTopTextActive: {
    color: theme.colors.primaryDark,
    fontWeight: '500',
  },
  dateChipBottomText: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.colors.textPrimary,
  },
  dateChipBottomTextActive: {
    color: theme.colors.primaryDark,
    fontWeight: '600',
  },
  calendarIconBtn: {
    width: 48,
    height: 52,
    borderRadius: 12,
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1,
    borderColor: theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  slotGroupContainer: {
    marginBottom: 14,
  },
  slotGroupTitle: {
    fontSize: 12,
    fontWeight: '500',
    color: theme.colors.textMuted,
    letterSpacing: 0.8,
    marginTop: 8,
    marginBottom: 8,
  },
  slotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 12,
  },
  slotBtn: {
    width: '48%',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
  },
  slotBtnActive: {
    backgroundColor: theme.colors.primaryDark,
    borderColor: theme.colors.primaryDark,
  },
  slotText: {
    fontSize: 12,
    fontWeight: '500',
    color: theme.colors.textPrimary,
    textAlign: 'center',
  },
  slotTextActive: {
    color: theme.colors.surface,
    fontWeight: '500',
  },
  reasonInput: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: theme.colors.textPrimary,
    minHeight: 84,
    textAlignVertical: 'top',
    marginBottom: 14,
  },
  summaryBox: {
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1,
    borderColor: theme.colors.primaryLight,
    borderRadius: 16,
    padding: 16,
    marginTop: 8,
    marginBottom: 16,
  },
  summaryTitle: {
    fontSize: 12,
    color: theme.colors.primaryDark,
    letterSpacing: 0.8,
    fontWeight: '600',
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 12,
    color: theme.colors.textMuted,
    letterSpacing: 0.5,
    fontWeight: '500',
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.colors.textPrimary,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.primaryLight,
    marginVertical: 10,
  },
  totalLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textPrimary,
  },
  totalValue: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.primaryDark,
  },
  footer: {
    backgroundColor: theme.colors.surface,
    borderTopWidth: 1,
    borderTopColor: theme.colors.surfaceBorder,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
  },
  proceedBtn: {
    backgroundColor: theme.colors.primaryDark,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  proceedBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.colors.surface,
  },
});

export default bookAppointmentStyles;
