import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const customBottomBarStyles = StyleSheet.create({
  container: {
    position: 'absolute',
    left: 14,
    right: 14,
    height: 64,
    borderRadius: 24,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.navBorder,
    paddingTop: 4,
    paddingBottom: 4,
    paddingHorizontal: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 8,
    zIndex: 99,
  },
  item: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  label: {
    fontSize: 10.5,
    fontWeight: '600',
    letterSpacing: 0.1,
    marginTop: 2,
    color: theme.colors.textSlate,
  },
  activeLabel: {
    color: theme.colors.primary,
    fontWeight: '700',
  },
  activeIndicatorDot: {
    width: 12,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: theme.colors.primary,
    marginBottom: 2,
  },
  inactiveIndicatorDot: {
    width: 12,
    height: 3,
    backgroundColor: theme.colors.transparent,
    marginBottom: 2,
  },
  activeIconContainer: {
    height: 28,
    paddingHorizontal: 10,
    minWidth: 38,
    maxWidth: 52,
    borderRadius: 14,
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inactiveIconContainer: {
    height: 28,
    paddingHorizontal: 10,
    minWidth: 38,
    maxWidth: 52,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badge: {
    position: 'absolute',
    top: -2,
    right: -4,
    backgroundColor: theme.colors.errorRed,
    borderRadius: 9,
    minWidth: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: theme.colors.surface,
  },
  badgeText: {
    color: theme.colors.surface,
    fontSize: 9,
    fontWeight: '700',
  },
});

export default customBottomBarStyles;
