import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
  },
  scrollView: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 30,
  },
  blockSpacing: {
    marginBottom: 16,
  },

  memberBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.mintBg,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.mintBdr,
  },
  memberBannerIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  memberBannerText: {
    flex: 1,
    fontSize: 12.5,
    fontWeight: '500',
    color: theme.colors.primaryDark,
  },
  memberBannerBack: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
  },
  memberBannerBackText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: theme.colors.primary,
  },

  // Section Header
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.textPrimary,
  },
  sectionSeeAll: {
    fontSize: 12.5,
    fontWeight: '600',
    color: theme.colors.primary,
  },

  // Profile Completion Card
  completionCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  completionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  completionTitle: {
    fontSize: 14.5,
    fontWeight: '600',
    color: theme.colors.textPrimary,
  },
  completionPercent: {
    fontSize: 13.5,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  progressBarBg: {
    height: 8,
    backgroundColor: theme.colors.surfaceSecondary,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 10,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.colors.primary,
    borderRadius: 4,
  },
  completionSubtitle: {
    fontSize: 12,
    color: theme.colors.textSlate,
    lineHeight: 16,
  },

  // Vitals Grid
  vitalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  vitalCard: {
    width: '48%',
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  vitalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  vitalIconWrapper: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vitalBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  vitalBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  vitalTitle: {
    fontSize: 12,
    color: theme.colors.textMuted,
    fontWeight: '500',
  },
  vitalValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginTop: 2,
  },
  vitalValue: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  vitalUnit: {
    fontSize: 11,
    color: theme.colors.textSlate,
    marginLeft: 4,
    fontWeight: '500',
  },

  // Find Specialist Banner Card
  specialistCard: {
    backgroundColor: theme.colors.primary,
    borderRadius: 20,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  specialistContent: {
    flex: 1,
    paddingRight: 12,
  },
  specialistTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.surface,
    marginBottom: 4,
  },
  specialistSubtitle: {
    fontSize: 12.5,
    color: 'rgba(255, 255, 255, 0.85)',
    marginBottom: 14,
    lineHeight: 17,
  },
  specialistBtn: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  specialistBtnText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  specialistIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Quick Access Grid
  quickAccessContainer: {
    marginBottom: 20,
  },
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  quickItemWrapper: {
    width: '25%',
    padding: 4,
    alignItems: 'center',
    marginBottom: 10,
  },
  quickItemCircle: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 6,
  },
  quickItemLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 14,
  },

  // Upcoming Appointments
  upcomingSection: {
    marginBottom: 20,
  },
  upcomingCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
    marginBottom: 10,
  },
  upcomingBadgeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  typeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1,
    borderColor: theme.colors.tealBdr,
  },
  typeBadgeText: {
    fontSize: 10.5,
    fontWeight: '600',
    color: theme.colors.primary,
    textTransform: 'uppercase',
  },
  upcomingDateText: {
    fontSize: 11.5,
    fontWeight: '500',
    color: theme.colors.textSlate,
  },
  upcomingDocRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  upcomingAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  upcomingAvatarText: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.colors.surface,
  },
  upcomingDocName: {
    fontSize: 14.5,
    fontWeight: '600',
    color: theme.colors.textPrimary,
  },
  upcomingDocSpec: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  upcomingActionRow: {
    flexDirection: 'row',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: theme.colors.surfaceBorder,
    paddingTop: 12,
  },
  upcomingPrimaryBtn: {
    flex: 1,
    backgroundColor: theme.colors.primary,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  upcomingPrimaryBtnText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: theme.colors.surface,
  },
  upcomingSecondaryBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    backgroundColor: theme.colors.surfaceSecondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  upcomingSecondaryBtnText: {
    fontSize: 12.5,
    fontWeight: '500',
    color: theme.colors.textSecondary,
  },

  // Daily Health Tips
  tipsContainer: {
    marginBottom: 24,
  },
  tipCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  tipTag: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: theme.colors.accentLight,
    marginBottom: 8,
  },
  tipTagText: {
    fontSize: 9.5,
    fontWeight: '600',
    color: theme.colors.accent,
    letterSpacing: 0.5,
  },
  tipTitle: {
    fontSize: 14.5,
    fontWeight: '600',
    color: theme.colors.textPrimary,
    marginBottom: 4,
  },
  tipDesc: {
    fontSize: 12.5,
    color: theme.colors.textSlate,
    lineHeight: 17,
  },

  // Empty Card Placeholder
  emptyBox: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  emptyBoxTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textSlate,
    marginBottom: 10,
  },
  emptyBoxBtn: {
    backgroundColor: theme.colors.primarySoft,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.tealBdr,
  },
  emptyBoxBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.primary,
  },

  // Profile Modal Overlay & Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFill,
  },
  modalContent: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    maxHeight: '90%',
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.colors.surfaceBorder,
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalScroll: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  profileSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  modalName: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginTop: 10,
  },
  relationBadge: {
    backgroundColor: theme.colors.mintBg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 6,
  },
  relationBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.primary,
  },

  infoList: {
    gap: 10,
    marginBottom: 20,
  },
  infoCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoRow: {
    flexDirection: 'row',
    gap: 10,
  },
  infoCardHalf: {
    flex: 1,
  },
  infoIcon: {
    fontSize: 18,
    marginRight: 10,
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textPrimary,
    marginTop: 2,
  },

  editProfileButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  editProfileText: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.surface,
  },

  // Members Card inside Profile Modal
  membersCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    marginBottom: 16,
    overflow: 'hidden',
  },
  membersCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
    backgroundColor: theme.colors.background,
  },
  membersCardTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.textMuted,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  membersManageText: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.primary,
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  memberRowActive: {
    backgroundColor: theme.colors.primarySoft,
  },
  memberRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
  },
  memberAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  memberAvatarImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 12,
  },
  memberAvatarText: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.surface,
  },
  memberInfo: {
    flex: 1,
  },
  memberName: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textPrimary,
  },
  memberRelation: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 1,
  },
  youBadge: {
    backgroundColor: theme.colors.mintBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginRight: 8,
  },
  youBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.primary,
  },
  memberActiveIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.colors.primary,
  },
  addMemberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: theme.colors.surfaceBorder,
  },
  addMemberPlusCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: theme.colors.primary,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  addMemberPlusText: {
    fontSize: 18,
    fontWeight: '400',
    color: theme.colors.primary,
    marginTop: -2,
  },
  addMemberLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.primary,
  },

  // Modal Action Buttons
  settingsButton: {
    backgroundColor: theme.colors.primarySoft,
    paddingVertical: 14,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.tealBdr,
    marginBottom: 10,
  },
  settingsIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  settingsText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  signOutButton: {
    backgroundColor: theme.colors.errorBg,
    paddingVertical: 14,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  signOutIcon: {
    fontSize: 16,
    marginRight: 8,
    color: theme.colors.errorRed,
  },
  signOutText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.errorRed,
  },

  // Notification Modal
  notifModalContent: {
    maxHeight: '85%',
    minHeight: '50%',
  },
  notifHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  notifTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  notifEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 32,
  },
  notifEmptyIcon: {
    fontSize: 48,
    marginBottom: 12,
  },
  notifEmptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: 6,
  },
  notifEmptySubtitle: {
    fontSize: 13,
    color: theme.colors.textSlate,
    textAlign: 'center',
    lineHeight: 18,
  },
  notifList: {
    paddingHorizontal: 16,
    paddingBottom: 40,
  },
  notifItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: theme.colors.background,
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  notifIconWrapper: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  notifIcon: {
    fontSize: 18,
  },
  notifBody: {
    flex: 1,
  },
  notifItemTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textPrimary,
    marginBottom: 2,
    textTransform: 'capitalize',
  },
  notifItemDesc: {
    fontSize: 12,
    color: theme.colors.textSlate,
    lineHeight: 16,
    marginBottom: 4,
  },
  notifItemTime: {
    fontSize: 11,
    color: theme.colors.textMuted,
    fontWeight: '500',
  },
});

export const UpcomingApptStyles = StyleSheet.create({
  section: {
    marginTop: 20,
    marginBottom: 8,
    width: '100%',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingHorizontal: 2,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '500',
    color: theme.colors.textPrimary,
    letterSpacing: -0.3,
  },
  countBadge: {
    backgroundColor: theme.colors.mintBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
  },
  countBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  seeAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.colors.primarySoft,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(15, 118, 110, 0.1)',
  },
  seeAllText: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.colors.primary,
  },

  // Column List Container
  listContainer: {
    width: '100%',
  },

  // Skeleton Loader Styles
  skeletonCard: {
    width: '100%',
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    padding: 16,
    marginBottom: 12,
    shadowColor: theme.colors.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  skeletonHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  skeletonPill: {
    width: 90,
    height: 22,
    borderRadius: 6,
    backgroundColor: theme.colors.surfaceSecondary,
  },
  skeletonTag: {
    width: 70,
    height: 22,
    borderRadius: 6,
    backgroundColor: theme.colors.surfaceSecondary,
  },
  skeletonDoctorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  skeletonAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.colors.surfaceSecondary,
    marginRight: 12,
  },
  skeletonDoctorDetails: {
    flex: 1,
    gap: 8,
  },
  skeletonLineLarge: {
    width: '60%',
    height: 14,
    borderRadius: 4,
    backgroundColor: theme.colors.surfaceSecondary,
  },
  skeletonLineSmall: {
    width: '40%',
    height: 10,
    borderRadius: 4,
    backgroundColor: theme.colors.surfaceSecondary,
  },
  skeletonLocationBar: {
    height: 38,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceSecondary,
    marginBottom: 12,
  },
  skeletonScheduleBar: {
    height: 38,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceSecondary,
    marginBottom: 14,
  },
  skeletonButton: {
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.colors.surfaceSecondary,
  },

  // Empty State Styles
  emptyCard: {
    width: '100%',
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    padding: 24,
    alignItems: 'center',
    shadowColor: theme.colors.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  emptyIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
  },
  emptyTitle: {
    fontSize: 14.5,
    fontWeight: '600',
    color: theme.colors.textPrimary,
    marginBottom: 4,
  },
  emptyText: {
    fontSize: 12.5,
    color: theme.colors.textSlate,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  emptyBtn: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 14,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  emptyBtnText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#FFFFFF',
  },

  // Appointment Card Styles
  card: {
    width: '100%',
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    marginBottom: 12,
    shadowColor: theme.colors.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  cardVideoAccent: {
    borderColor: 'rgba(15, 118, 110, 0.16)',
  },
  cardClinicAccent: {
    borderColor: 'rgba(2, 132, 199, 0.18)',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  typePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
  },
  typePillVideo: {
    backgroundColor: theme.colors.mintBg,
    borderColor: theme.colors.mintBdr,
  },
  typePillClinic: {
    backgroundColor: theme.colors.accentLight,
    borderColor: '#BAE6FD',
  },
  typePillText: {
    fontSize: 9.5,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  typePillTextVideo: {
    color: theme.colors.primary,
  },
  typePillTextClinic: {
    color: theme.colors.accent,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  todayBadge: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FDE68A',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  todayBadgeText: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#B45309',
    letterSpacing: 0.3,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
  },
  statusBadgeText: {
    fontSize: 9.5,
    fontWeight: '600',
  },
  livePulsingDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#16A34A',
  },

  // Doctor Info Block
  doctorInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  avatarWrapper: {
    position: 'relative',
    marginRight: 12,
  },
  avatarImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.colors.surfaceSecondary,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  avatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  avatarPlaceholderVideo: {
    backgroundColor: theme.colors.primary,
  },
  avatarPlaceholderClinic: {
    backgroundColor: theme.colors.accent,
  },
  avatarInitials: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  activeDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 13,
    height: 13,
    borderRadius: 6.5,
    backgroundColor: theme.colors.success,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  doctorDetails: {
    flex: 1,
  },
  doctorName: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.textPrimary,
    marginBottom: 3,
    letterSpacing: -0.2,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  specialtyChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.colors.primarySoft,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(15, 118, 110, 0.12)',
  },
  specialtyText: {
    fontSize: 9,
    fontWeight: '500',
    color: theme.colors.primary,
  },
  patientChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.colors.surfaceSecondary,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  patientText: {
    fontSize: 9,
    fontWeight: '400',
    color: theme.colors.textSlate,
  },

  // Middle Context Rows
  locationBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F9FF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E0F2FE',
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 10,
    gap: 8,
  },
  locationIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#E0F2FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationTextContainer: {
    flex: 1,
  },
  clinicNameText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0369A1',
    marginBottom: 2,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  clinicAddressText: {
    fontSize: 11,
    color: theme.colors.textSlate,
    flex: 1,
  },
  telehealthBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 10,
    gap: 8,
  },
  telehealthIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: theme.colors.mintBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  telehealthTextContainer: {
    flex: 1,
  },
  telehealthTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.primaryDark,
    marginBottom: 1,
  },
  telehealthSub: {
    fontSize: 11,
    color: theme.colors.textSlate,
  },

  // Schedule Ticket Bar
  scheduleBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
    justifyContent: 'space-between',
  },
  scheduleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  scheduleIconWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scheduleItemText: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.colors.textPrimary,
  },
  scheduleDivider: {
    width: 1,
    height: 16,
    backgroundColor: theme.colors.surfaceBorder,
  },

  // Card Footer & Action Buttons
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 9,
    borderRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  actionButtonVideo: {
    backgroundColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
  },
  actionButtonClinic: {
    backgroundColor: theme.colors.accent,
    shadowColor: theme.colors.accent,
  },
  actionButtonText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  detailsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    backgroundColor: theme.colors.surfaceSecondary,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  detailsButtonText: {
    fontSize: 10,
    fontWeight: '600',
    color: theme.colors.textSecondary,
  },
});

export default dashboardStyles;
