import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const doctorStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 15,
    color: theme.colors.textSecondary,
    fontWeight: '500',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 120,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingTop: 48,
    paddingBottom: 24,
  },
  emptyIconWrapper: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: 8,
  },
  emptyDescription: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 24,
  },
  emptyActionButton: {
    marginTop: 24,
    backgroundColor: theme.colors.primaryDark,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyActionButtonText: {
    color: theme.colors.surface,
    fontWeight: '700',
    fontSize: 14,
  },
  doctorsList: {
    gap: 14,
  },
  doctorCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    shadowColor: 'rgba(15, 23, 42, 0.08)',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  doctorMainInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  doctorAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: theme.colors.primaryDark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doctorAvatarImage: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: theme.colors.surfaceSecondary,
  },
  doctorAvatarText: {
    color: theme.colors.surface,
    fontWeight: '700',
    fontSize: 16,
  },
  doctorDetails: {
    flex: 1,
    minWidth: 0,
  },
  doctorName: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  doctorSpecialization: {
    marginTop: 2,
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  clinicName: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: theme.colors.primaryDark,
    textTransform: 'uppercase',
  },
  scheduledBox: {
    marginTop: 14,
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 12,
    padding: 12,
  },
  pastBox: {
    marginTop: 12,
    backgroundColor: theme.colors.surfaceSecondary,
    borderRadius: 12,
    padding: 12,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    color: theme.colors.textSecondary,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  upcomingList: {
    gap: 10,
  },
  upcomingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  upcomingMeta: {
    flex: 1,
    gap: 4,
  },
  typeBadge: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.primaryDark,
    letterSpacing: 0.3,
  },
  scheduledRow: {
    flexDirection: 'row',
    gap: 16,
  },
  scheduledCol: {
    flex: 1,
  },
  metaIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  metaLbl: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.colors.textSecondary,
    letterSpacing: 0.4,
  },
  metaVal: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  pastList: {
    gap: 10,
  },
  pastRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pastDate: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textPrimary,
  },
  lastVisit: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.primaryDark,
    letterSpacing: 0.4,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  profileBtn: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: theme.colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  profileBtnTxt: {
    color: theme.colors.primaryDark,
    fontWeight: '700',
    fontSize: 14,
  },
  bookBtn: {
    flex: 1,
    backgroundColor: theme.colors.primaryDark,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  bookBtnTxt: {
    color: theme.colors.surface,
    fontWeight: '700',
    fontSize: 14,
  },
  findCard: {
    marginTop: 16,
    backgroundColor: theme.colors.surfaceSecondary,
    borderRadius: 16,
    paddingVertical: 28,
    paddingHorizontal: 24,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    alignItems: 'center',
  },
  findPlus: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: 'rgba(15, 23, 42, 0.08)',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  findTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: 8,
    textAlign: 'center',
  },
  findSub: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    lineHeight: 20,
    marginBottom: 16,
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  findLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  findLink: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.primaryDark,
  },
  bottomPadding: {
    height: 24,
  },
});

export default doctorStyles;
