import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const navigationStyles = StyleSheet.create({
  tabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.surface,
    borderTopWidth: 1,
    borderTopColor: theme.colors.navBorder,
    paddingTop: 6,
    paddingHorizontal: 6,
    shadowColor: theme.colors.primaryDark,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 10,
    zIndex: 99,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  tabLabel: {
    fontSize: 10.5,
    fontWeight: '600',
    letterSpacing: 0.1,
    marginTop: 2,
  },
  activeIndicatorDot: {
    width: 12,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: theme.colors.primary,
    marginBottom: 2,
  },
  inactiveIndicatorDot: {
    width: 12,
    height: 3,
    backgroundColor: theme.colors.transparent,
    marginBottom: 2,
  },
  activeIconContainer: {
    height: 28,
    paddingHorizontal: 10,
    minWidth: 38,
    maxWidth: 52,
    borderRadius: 14,
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inactiveIconContainer: {
    height: 28,
    paddingHorizontal: 10,
    minWidth: 38,
    maxWidth: 52,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
