import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const prescriptionsStyles = StyleSheet.create({
  // Main Screen Container
  screen: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 110,
    flexGrow: 1,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loadingText: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginTop: 12,
  },
  bellBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Member Banner
  memberBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 12,
  },
  memberBannerText: {
    fontSize: 13,
    color: theme.colors.primaryDark,
    fontWeight: '600',
  },

  // Search & Filter Row
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    paddingHorizontal: 14,
    height: 48,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: theme.colors.textPrimary,
    paddingVertical: 8,
    marginLeft: 8,
  },
  filterBtn: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.tealBdr,
  },
  filterBtnActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },

  // Prescription List Card
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  dateCol: {
    width: 48,
    alignItems: 'center',
    marginRight: 14,
  },
  dateDay: {
    fontSize: 22,
    fontWeight: '800',
    color: theme.colors.textPrimary,
    lineHeight: 26,
  },
  dateMonth: {
    fontSize: 11,
    color: theme.colors.textMuted,
    fontWeight: '700',
    letterSpacing: 0.6,
    marginTop: 2,
  },
  cardMid: {
    flex: 1,
    paddingRight: 8,
  },
  doctorName: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: 3,
  },
  rxId: {
    fontSize: 12,
    color: theme.colors.textMuted,
  },
  cardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Empty State
  emptyWrap: {
    alignItems: 'center',
    paddingTop: 48,
    paddingHorizontal: 24,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  refreshBtn: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 12,
  },
  refreshText: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.surface,
  },

  // Filter Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    justifyContent: 'flex-end',
  },
  filterModalContent: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    maxHeight: '90%',
  },
  filterHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
  },
  filterTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  filterResetLink: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.primary,
  },
  filterScroll: {
    padding: 20,
  },
  filterSectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.primary,
    marginBottom: 12,
  },
  filterSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 46,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    marginBottom: 20,
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: theme.colors.surfaceBorder,
    marginBottom: 10,
    backgroundColor: theme.colors.surface,
  },
  radioRowSelected: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primarySoft,
  },
  radioLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textPrimary,
  },
  radioLabelSelected: {
    color: theme.colors.primaryDark,
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: theme.colors.textMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterSelected: {
    borderColor: theme.colors.primary,
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: theme.colors.primary,
  },
  customCard: {
    marginTop: 12,
    backgroundColor: theme.colors.background,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  customTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: 2,
  },
  customSub: {
    fontSize: 12,
    color: theme.colors.textMuted,
  },
  dateRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  dateField: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  dateFieldLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.textMuted,
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  dateFieldValue: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dateFieldText: {
    fontSize: 13,
    color: theme.colors.textPrimary,
    fontWeight: '600',
  },
  filterFooter: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: theme.colors.surfaceBorder,
    gap: 12,
  },
  applyBtn: {
    backgroundColor: theme.colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
  },
  applyBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.surface,
  },

  // Prescription Detail Screen Styles
  detailScroll: { flex: 1, backgroundColor: theme.colors.background },
  detailContent: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 60 },
  rxIdBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.surface,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  rxIdLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: theme.colors.textSecondary,
  },
  rxIdValueWrap: {
    backgroundColor: theme.colors.mintBg,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  rxIdValue: { fontSize: 13, fontWeight: '800', color: theme.colors.primary },

  detailCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  patientRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  avatarCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: theme.colors.surface, fontWeight: '800', fontSize: 18 },
  patientName: { fontSize: 16, fontWeight: '700', color: theme.colors.textPrimary },
  badgeRow: { flexDirection: 'row', gap: 8, marginTop: 6 },
  metaBadge: {
    backgroundColor: theme.colors.background,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  metaBadgeText: { fontSize: 12, color: theme.colors.textSecondary, fontWeight: '600' },

  doctorRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  doctorSpec: { fontSize: 13, color: theme.colors.textSecondary, marginTop: 2 },
  clinicName: {
    marginTop: 6,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: theme.colors.primary,
  },
  dateBadge: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
    minWidth: 86,
    borderWidth: 1,
    borderColor: theme.colors.tealBdr,
  },
  dateBadgeLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.textSecondary,
    letterSpacing: 0.4,
  },
  dateBadgeValue: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.primary,
  },

  detailSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    marginBottom: 8,
  },
  detailSectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.7,
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
  },
  countBadge: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  countBadgeText: { fontSize: 10, fontWeight: '700', color: theme.colors.primary },

  bodyText: {
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.textSecondary,
  },
  vitalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
  },
  vitalCard: {
    width: '48%',
    backgroundColor: theme.colors.background,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  vitalLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    color: theme.colors.textMuted,
    marginBottom: 4,
  },
  vitalValue: { fontSize: 16, fontWeight: '800', color: theme.colors.primary },
  vitalValueDanger: { color: theme.colors.danger },
  vitalUnit: { fontSize: 11, fontWeight: '600', color: theme.colors.textMuted },

  medTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  medName: { flex: 1, fontSize: 15, fontWeight: '700', color: theme.colors.textPrimary },
  medScheduleWrap: { alignItems: 'flex-end' },
  medSchedule: { fontSize: 15, fontWeight: '800', color: theme.colors.primary },
  medScheduleSub: { fontSize: 11, color: theme.colors.textMuted, marginTop: 2 },
  medMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
  },
  medMetaText: { fontSize: 13, color: theme.colors.textSlate, fontWeight: '600' },
  medNotes: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    color: theme.colors.textSecondary,
  },
  sosRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
  },
  sosText: { fontSize: 12, fontWeight: '700', color: theme.colors.danger },

  diagnosisText: { fontSize: 15, fontWeight: '700', color: theme.colors.primary, lineHeight: 22 },

  adviceCard: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.colors.tealBdr,
  },
  adviceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  adviceLabel: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
    color: theme.colors.primary,
  },
  adviceText: { fontSize: 14, lineHeight: 20, color: theme.colors.textSecondary },

  followUpCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  followUpLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  followUpIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  followUpLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    color: theme.colors.textMuted,
  },
  followUpValue: {
    marginTop: 2,
    fontSize: 15,
    fontWeight: '800',
    color: theme.colors.primary,
  },

  pdfBtn: {
    height: 52,
    borderRadius: 14,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 40,
  },
  pdfBtnText: {
    color: theme.colors.surface,
    fontSize: 15,
    fontWeight: '700',
  },
});

export default prescriptionsStyles;
