import { Invoice } from '../../typescripts/types/invoice.types';

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv_101',
    invoiceNumber: 'INV-2026-0894',
    patientId: 'pat_001',
    patientName: 'John Doe',
    patientPhone: '+91 98765 43210',
    patientEmail: 'john.doe@example.com',
    appointmentId: 'apt_501',
    appointmentDate: '2026-09-24T10:30:00Z',
    createdDate: '2026-09-24T11:00:00Z',
    dueDate: '2026-09-24T11:00:00Z',
    doctorName: 'Dr. Sarah Jenkins',
    doctorSpecialty: 'Cardiologist',
    clinicName: 'Apollo Heart Institute',
    clinicAddress: '42 Health Avenue, Metro City',
    currency: 'INR',
    items: [
      {
        id: 'item_1',
        name: 'Cardiology Specialist Consultation',
        qty: '1',
        price: '1200',
        discount: '0',
        discount_type: 'flat',
        tax_percent: '18',
        total: 1200,
      },
      {
        id: 'item_2',
        name: 'Electrocardiogram (ECG) Report',
        qty: '1',
        price: '500',
        discount: '200',
        discount_type: 'flat',
        tax_percent: '0',
        total: 300,
      },
    ],
    subtotal: 1500,
    totalDiscount: 200,
    cgst: 108,
    sgst: 108,
    igst: 0,
    grandTotal: 1500,
    paymentMode: 'UPI',
    status: 'Paid',
    notes: 'Payment received via Google Pay. Thank you!',
  },
  {
    id: 'inv_102',
    invoiceNumber: 'INV-2026-0852',
    patientId: 'pat_001',
    patientName: 'John Doe',
    patientPhone: '+91 98765 43210',
    patientEmail: 'john.doe@example.com',
    appointmentId: 'apt_502',
    appointmentDate: '2026-09-18T16:15:00Z',
    createdDate: '2026-09-18T16:45:00Z',
    dueDate: '2026-09-25T23:59:59Z',
    doctorName: 'Dr. Rajesh Sharma',
    doctorSpecialty: 'Dermatologist',
    clinicName: 'Skin Care & Laser Center',
    clinicAddress: '15 Lotus Park, South Wing',
    currency: 'INR',
    items: [
      {
        id: 'item_3',
        name: 'Dermatology Follow-up Consultation',
        qty: '1',
        price: '850',
        discount: '0',
        discount_type: 'flat',
        tax_percent: '0',
        total: 850,
      },
    ],
    subtotal: 850,
    totalDiscount: 0,
    cgst: 0,
    sgst: 0,
    igst: 0,
    grandTotal: 850,
    paymentMode: 'Card',
    status: 'Pending',
    notes: 'Payment scheduled via Card on file.',
  },
  {
    id: 'inv_103',
    invoiceNumber: 'INV-2026-0791',
    patientId: 'pat_001',
    patientName: 'John Doe',
    patientPhone: '+91 98765 43210',
    patientEmail: 'john.doe@example.com',
    appointmentId: 'apt_503',
    appointmentDate: '2026-09-02T11:00:00Z',
    createdDate: '2026-09-02T11:30:00Z',
    dueDate: '2026-09-02T11:30:00Z',
    doctorName: 'Dr. Priya Nair',
    doctorSpecialty: 'General Physician',
    clinicName: 'City Care Clinic',
    clinicAddress: '88 MG Road, Central Plaza',
    currency: 'INR',
    items: [
      {
        id: 'item_4',
        name: 'General Health Checkup & Prescription',
        qty: '1',
        price: '600',
        discount: '50',
        discount_type: 'flat',
        tax_percent: '0',
        total: 550,
      },
      {
        id: 'item_5',
        name: 'Blood Glucose Test (Random)',
        qty: '1',
        price: '150',
        discount: '0',
        discount_type: 'flat',
        tax_percent: '0',
        total: 150,
      },
    ],
    subtotal: 750,
    totalDiscount: 50,
    cgst: 0,
    sgst: 0,
    igst: 0,
    grandTotal: 700,
    paymentMode: 'Cash',
    status: 'Paid',
    notes: 'Paid at counter receipt #8819.',
  },
  {
    id: 'inv_104',
    invoiceNumber: 'INV-2026-0640',
    patientId: 'pat_001',
    patientName: 'John Doe',
    patientPhone: '+91 98765 43210',
    patientEmail: 'john.doe@example.com',
    appointmentId: 'apt_504',
    appointmentDate: '2026-08-14T14:00:00Z',
    createdDate: '2026-08-14T14:30:00Z',
    dueDate: '2026-08-20T23:59:59Z',
    doctorName: 'Dr. Amit Patel',
    doctorSpecialty: 'Orthopedic Surgeon',
    clinicName: 'Joint & Bone Health Center',
    clinicAddress: '102 Wellness Tower, Ring Road',
    currency: 'INR',
    items: [
      {
        id: 'item_6',
        name: 'Orthopedic Consultation & Knee Assessment',
        qty: '1',
        price: '1100',
        discount: '0',
        discount_type: 'flat',
        tax_percent: '0',
        total: 1100,
      },
    ],
    subtotal: 1100,
    totalDiscount: 0,
    cgst: 0,
    sgst: 0,
    igst: 0,
    grandTotal: 1100,
    paymentMode: 'Online',
    status: 'Overdue',
    notes: 'Invoice reminder sent on Aug 21, 2026.',
  },
  {
    id: 'inv_105',
    invoiceNumber: 'INV-2026-0518',
    patientId: 'pat_001',
    patientName: 'John Doe',
    patientPhone: '+91 98765 43210',
    patientEmail: 'john.doe@example.com',
    appointmentId: 'apt_505',
    appointmentDate: '2026-07-28T09:45:00Z',
    createdDate: '2026-07-28T10:15:00Z',
    dueDate: '2026-07-28T10:15:00Z',
    doctorName: 'Dr. Meera Sen',
    doctorSpecialty: 'Pediatrician',
    clinicName: 'Sunshine Children Clinic',
    clinicAddress: '31 Sunshine Enclave, North Sector',
    currency: 'INR',
    items: [
      {
        id: 'item_7',
        name: 'Routine Child Vaccination & Consultation',
        qty: '1',
        price: '950',
        discount: '100',
        discount_type: 'flat',
        tax_percent: '0',
        total: 850,
      },
    ],
    subtotal: 950,
    totalDiscount: 100,
    cgst: 0,
    sgst: 0,
    igst: 0,
    grandTotal: 850,
    paymentMode: 'UPI',
    status: 'Paid',
    notes: 'Paid via NetBanking / UPI.',
  },
];
